/**
 * Created by jakub on 07.04.17.
 */
module employees {
  export enum EReceptionNoteType{
    CREATED_DOCK_RECEPTION = <any>"CREATED_DOCK_RECEPTION",
    TRANCHE = <any>"TRANCHE",
    TRANSFER = <any>"TRANSFER",
    SALE_OF_RECEIVABLES = <any>"SALE_OF_RECEIVABLES",
    NORMALIZATION = <any>"NORMALIZATION",
    NORMALIZATION_DEPARTMENT = <any>"NORMALIZATION_DEPARTMENT",
    IT_DEPARTMENT = <any>"IT_DEPARTMENT",
    TRANCHE_INFO = <any>"TRANCHE_INFO",
    DELETE_TRANCHE = <any>"DELETE_TRANCHE"
  }
}